Horizontal-org/Tella-Android

mobile/build.gradle, mobile/src/main/java/rs/readahead/washington/mobile/data/sharedpref/Preferences.java, mobile/src/main/java/rs/readahead/washington/mobile/data/sharedpref/SharedPrefs.java, mobile/src/main/java/rs/readahead/washington/mobile/presentation/entity/VideoResolutionOption.java, mobile/src/main/java/rs/readahead/washington/mobile/util/DialogsUtil.java, mobile/src/main/java/rs/readahead/washington/mobile/util/VideoResolutionManager.java, mobile/src/main/java/rs/readahead/washington/mobile/views/activity/CameraActivity.java, mobile/src/main/java/rs/readahead/washington/mobile/views/activity/QuestionAttachmentActivity.java, mobile/src/main/java/rs/readahead/washington/mobile/views/collect/widgets/ImageWidget.java, mobile/src/main/java/rs/readahead/washington/mobile/views/collect/widgets/VideoWidget.java, mobile/src/main/res/drawable/ic_tune_white_24dp.xml, mobile/src/main/res/layout/activity_camera.xml, mobile/src/main/res/layout/video_resolution_dialog_radio_button_item.xml, mobile/src/main/res/layout/video_resolution_setting_dialog.xml, mobile/src/main/res/values-be/strings.xml, mobile/src/main/res/values-es/strings.xml, mobile/src/main/res/values-fr/strings.xml, mobile/src/main/res/values-pt/strings.xml, mobile/src/main/res/values-ru/strings.xml, mobile/src/main/res/values/strings.xml, mobile/src/main/res/values/styles.xml
Implementation of the option to select video recording resolution.
=> Video recording resolution

.gitignore, build.gradle, mobile/build.gradle, mobile/src/main/AndroidManifest.xml
Migrates crash reporting from Fabric.io to Firebase.
=> Migrate to Firebase.

mobile/src/main/java/rs/readahead/washington/mobile/data/entity/MetadataEntity.java, mobile/src/main/java/rs/readahead/washington/mobile/data/entity/mapper/EntityMapper.java, mobile/src/main/java/rs/readahead/washington/mobile/domain/entity/Metadata.java, mobile/src/main/java/rs/readahead/washington/mobile/javarosa/FormParser.java, mobile/src/main/java/rs/readahead/washington/mobile/javarosa/FormUtils.java, mobile/src/main/java/rs/readahead/washington/mobile/mvp/contract/IAudioCapturePresenterContract.java, mobile/src/main/java/rs/readahead/washington/mobile/mvp/presenter/AudioCapturePresenter.java, mobile/src/main/java/rs/readahead/washington/mobile/views/activity/AudioRecordActivity2.java, mobile/src/main/java/rs/readahead/washington/mobile/views/activity/CameraActivity.java, mobile/src/main/java/rs/readahead/washington/mobile/views/activity/MetadataActivity.java, mobile/src/main/java/rs/readahead/washington/mobile/views/collect/widgets/GeoPointHiddenWidget.java, mobile/src/main/java/rs/readahead/washington/mobile/views/collect/widgets/GeoPointWidget.java, mobile/src/main/java/rs/readahead/washington/mobile/views/collect/widgets/StringHiddenWidget.java, mobile/src/main/java/rs/readahead/washington/mobile/views/collect/widgets/StringWidget.java, mobile/src/main/java/rs/readahead/washington/mobile/views/collect/widgets/WidgetFactory.java, mobile/src/main/res/values/config.xml
Put metadata text of the image on the supplied field (to the next filed wich starts with "_textmetadata_").
Put metadata text of the image on the supplied field (to the next filed wich starts with  "_geometadata_").
Hide supplied fields (make hidden widgets).
=> Attach file metadata and file location to hidden fields in Kobo form

mobile/src/main/java/rs/readahead/washington/mobile/views/activity/CameraActivity.java, mobile/src/main/java/rs/readahead/washington/mobile/views/custom/CameraGridButton.java, mobile/src/main/res/drawable/ic_grid_off_white_24dp.xml, mobile/src/main/res/drawable/ic_grid_on_white_24dp.xml, mobile/src/main/res/layout/activity_camera.xml
add a button to show/hide a 3x3 grid in the camera view
=> #10 Show camera grid

.github/issues_templates.md/bug_fix_template.md, .github/issues_templates.md/documentation_change_template.md, .github/issues_templates.md/new_feature_template.md, .github/pull_request_template.md
Adding templates for pull requests and contributor issues
=> Add issues and pull request templates

.github/issues_templates.md/config.yml
Pull requests should be opened against the `master` branch. For more information on contributing to Tella documentation, see the [Contributor Guidelines]().
**Description:**
Adds a config file, so users can use templates
**Select the type of change(s) made in this pull request:**
---------------------------------------------------------------------------------------------------------
Fixes #issue-number
*
*
*
=> Create config.yml for issues templates

mobile/src/main/java/rs/readahead/washington/mobile/media/MediaFileHandler.java
Link : https://console.firebase.google.com/u/0/project/tella-a8c5e/crashlytics/app/android:org.hzontal.tella/issues/1c1baafab263661d54acc841bad66356?time=last-twenty-four-hours&sessionEventKey=5FCFDDA1030000011F0487519ABEA6DA_1482426120716802968
=> Fix file path Android Q problem

mobile/src/main/res/values-kn/strings.xml, mobile/src/main/res/values-ml/strings.xml, mobile/src/main/res/values-ta/strings.xml, mobile/src/main/res/values/config.xml
**Description:**
Added Malayalam, Kannada, and Tamil language.
**Select the type of change(s) made in this pull request:**
----------------------------------------------------------------------------------------
Added Malayalam, Kannada, and Tamil language, updated language menu.
=> Added Malayalam, Kannada and Tamil language.

mobile/src/main/java/rs/readahead/washington/mobile/MyApplication.java
Fixes crash on older devices.
**Select the type of change(s) made in this pull request:**
=> Fix startup crash on older devices.

mobile/src/main/java/rs/readahead/washington/mobile/mvp/presenter/CheckOdkServerPresenter.java, mobile/src/main/java/rs/readahead/washington/mobile/mvp/presenter/CheckTUSServerPresenter.java
Clear cache on server credentials check.
=> Clear cache on server credentials check

tella-locking-ui/src/main/java/com/hzontal/tella_locking_ui/ui/pin/calculator/CalculatorActivity.kt, tella-locking-ui/src/main/java/com/hzontal/tella_locking_ui/ui/pin/pinview/CalculatorKeyView.kt, tella-locking-ui/src/main/java/com/hzontal/tella_locking_ui/ui/pin/pinview/OnKeyBoardClickListener.kt
https://app.asana.com/0/1199579928442791/1200377292329620/f
=> Clear result and entry on "AC" click

mobile/src/main/java/rs/readahead/washington/mobile/views/activity/SettingsActivity.java, mobile/src/main/java/rs/readahead/washington/mobile/views/activity/onboarding/OnBoardIntroFragment.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/activity/onboarding/OnBoardLockFragment.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/activity/onboarding/OnBoardSetUpFragment.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/base_ui/BaseFragment.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/VaultFragment.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/settings/GeneralSettings.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/settings/LanguageSettings.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/settings/OnFragmentSelected.kt, mobile/src/main/res/drawable/check_tiger_orange.xml, mobile/src/main/res/layout/fragment_language_settings.xml, mobile/src/main/res/layout/language_item_layout.xml, mobile/src/main/res/navigation/settings_navigation.xml, shared-ui/src/main/java/org/hzontal/shared_ui/bottomsheet/CustomBottomSheetFragment.kt
Implemented general settings except app customization.
=> general-settings

mobile/.gitignore, mobile/src/main/java/rs/readahead/washington/mobile/data/sharedpref/Preferences.java, mobile/src/main/java/rs/readahead/washington/mobile/data/sharedpref/SharedPrefs.java, mobile/src/main/java/rs/readahead/washington/mobile/views/activity/CameraActivity.java, mobile/src/main/java/rs/readahead/washington/mobile/views/activity/MainActivity.java, mobile/src/main/java/rs/readahead/washington/mobile/views/settings/GeneralSettings.kt, mobile/src/main/res/layout/fragment_general_settings.xml, mobile/src/main/res/values-ar/strings.xml, mobile/src/main/res/values-be/strings.xml, mobile/src/main/res/values-es/strings.xml, mobile/src/main/res/values-fr/strings.xml, mobile/src/main/res/values-in/strings.xml, mobile/src/main/res/values-kn/strings.xml, mobile/src/main/res/values-ml/strings.xml, mobile/src/main/res/values-my-rMM/strings.xml, mobile/src/main/res/values-pt/strings.xml, mobile/src/main/res/values-ru/strings.xml, mobile/src/main/res/values-ta/strings.xml, mobile/src/main/res/values/strings.xml, mobile/src/main/res/values/styles.xml, shared-ui/src/main/res/drawable/rounded_light_purple_background.xml
T 397 - home nav button should be selected after camera shuts down and after file info screen
T 420 - fix settings card background
T 445 - add switches for recent files and favorite forms
=> fixes-alpha3

mobile/src/main/java/rs/readahead/washington/mobile/views/activity/MainActivity.java, mobile/src/main/java/rs/readahead/washington/mobile/views/base_ui/BaseFragment.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/vault/attachements/AttachmentsFragment.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/vault/attachements/OnNavBckListener.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/vault/home/HomeVaultFragment.kt, mobile/src/main/res/layout/fragment_vault_attachments.xml, mobile/src/main/res/layout/item_vault_attachmenets.xml, mobile/src/main/res/layout/item_vault_attachment_grid.xml, mobile/src/main/res/layout/item_vault_attachment_hor.xml, shared-ui/src/main/res/layout/component_toolbar.xml
FIX : T468 Homescreen should be scrolled up
FIX : T467 Change Back arrow behavior in Vault
Fix T471 Display issue in Move mode
Fix T451 -  Vault spacing according to size guide
=> Vault Alpha 5 fixes

mobile/build.gradle, mobile/src/main/java/rs/readahead/washington/mobile/media/MediaFileHandler.java, mobile/src/main/java/rs/readahead/washington/mobile/util/Extensions.kt, mobile/src/main/java/rs/readahead/washington/mobile/util/LockTimeoutManager.java, mobile/src/main/java/rs/readahead/washington/mobile/views/activity/MainActivity.java, mobile/src/main/java/rs/readahead/washington/mobile/views/activity/onboarding/OnBoardFilesFragment.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/base_ui/BaseActivity.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/MicFragment.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/vault/adapters/attachments/AttachmentsRecycleViewAdapter.java, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/vault/attachements/AttachmentsFragment.kt, mobile/src/main/res/color/bottom_nav_item_color.xml, mobile/src/main/res/layout/activity_main2.xml, mobile/src/main/res/layout/fragment_vault_attachments.xml, mobile/src/main/res/layout/item_vault_attachment_grid.xml, mobile/src/main/res/layout/item_vault_attachment_hor.xml, mobile/src/main/res/layout/onboard_calculator_fragment.xml, mobile/src/main/res/layout/onboard_camera_fragment.xml, mobile/src/main/res/layout/onboard_connected_server.xml, mobile/src/main/res/layout/onboard_files_fragment.xml, mobile/src/main/res/layout/onboard_hide_set_fragment.xml, mobile/src/main/res/layout/onboard_hide_tella_fragment.xml, mobile/src/main/res/layout/onboard_lock_fragment.xml, mobile/src/main/res/layout/onboard_lock_set_fragment.xml, mobile/src/main/res/layout/onboard_recorder_fragment.xml, mobile/src/main/res/layout/onboard_setup_fragment.xml, shared-ui/src/main/java/org/hzontal/shared_ui/bottomsheet/VaultSheetUtils.kt, shared-ui/src/main/res/layout/component_toolbar.xml, tella-locking-ui/src/main/java/com/hzontal/tella_locking_ui/ui/pattern/PatternSetConfirmActivity.kt, tella-locking-ui/src/main/res/layout/activity_pin.xml, tella-locking-ui/src/main/res/values/colors.xml
T536 - Reduce Move box margins
T535 - Move mode colours
T532 - Select all button does not work
T519 - Fix bottom nav colours
T543 - Increase app bar title size
T444 - Change timeout to 1min when granting permissions & importing files (build 65 feedback)
T516 - Fix Select Mode flow
FIX T510 - Onboarding back/next buttons need to be consistently located
T551 - Fix "cancel" button in Lock setup
T514 - Onboarding lock setup should say "BACK", not "CANCEL"
T483 - Restrict file type that can be imported
T524 - Fix PIN keypad spacing
T531 - Fix Vault upper menu spacing
T533 - Increase checkbox size
Upgrade Min API to 19.
=> Alpha 7 fixes 

mobile/src/main/java/rs/readahead/washington/mobile/data/uwazi/UwaziConstants.java, mobile/src/main/java/rs/readahead/washington/mobile/util/DialogsUtil.java, mobile/src/main/java/rs/readahead/washington/mobile/views/activity/CameraActivity.java, mobile/src/main/java/rs/readahead/washington/mobile/views/activity/CollectFormEntryActivity.java, mobile/src/main/java/rs/readahead/washington/mobile/views/adapters/CollectDraftFormInstanceRecycleViewAdapter.java, mobile/src/main/java/rs/readahead/washington/mobile/views/adapters/CollectSubmittedFormInstanceRecycleViewAdapter.java, mobile/src/main/java/rs/readahead/washington/mobile/views/collect/widgets/AudioWidget.java, mobile/src/main/java/rs/readahead/washington/mobile/views/collect/widgets/DateWidget.java, mobile/src/main/java/rs/readahead/washington/mobile/views/collect/widgets/GeoPointWidget.java, mobile/src/main/java/rs/readahead/washington/mobile/views/collect/widgets/ImageWidget.java, mobile/src/main/java/rs/readahead/washington/mobile/views/collect/widgets/SelectOneWidget.java, mobile/src/main/java/rs/readahead/washington/mobile/views/collect/widgets/SignatureWidget.java, mobile/src/main/java/rs/readahead/washington/mobile/views/collect/widgets/TimeWidget.java, mobile/src/main/java/rs/readahead/washington/mobile/views/collect/widgets/VideoWidget.java, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/forms/BlankFormsListFragment.java, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/uwazi/UwaziFragment.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/uwazi/attachments/AttachmentsActivitySelector.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/uwazi/widgets/UwaziImageWidget.java, mobile/src/main/res/layout/draft_collect_form_instance_row.xml, mobile/src/main/res/layout/fragment_collect_main.xml, mobile/src/main/res/menu/signature_menu.xml, mobile/src/main/res/values-ar/strings.xml, mobile/src/main/res/values-es/strings.xml, mobile/src/main/res/values-fr/strings.xml, mobile/src/main/res/values/strings.xml, mobile/src/main/res/values/styles.xml
- Fix adding a files to the odk forms
- Minor UI fixes
=> Update odk forms flow

mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/uwazi/widgets/UwaziMultiSelectWidget.java, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/uwazi/widgets/UwaziSelectOneWidget.java, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/vault/attachements/AttachmentsFragment.kt
Fix T734 - Bug: app crashes when opening template
=> Fix T734 / T735

mobile/src/main/res/values-pt/strings.xml, mobile/src/main/res/values-pt/vault_strings.xml, mobile/src/main/res/values-ru/strings.xml, mobile/src/main/res/values/vault_strings.xml, shared-ui/src/main/res/values/styles.xml, tella-locking-ui/src/main/res/values-in/strings.xml, tella-locking-ui/src/main/res/values-pt/strings.xml
T742 - Typos on two screen at the beginning
T750 - Typo: "audios" → "audio"
T616 - Bottom sheet menu items need to be larger
=> Bug fixing

mobile/src/main/java/rs/readahead/washington/mobile/media/MediaFileHandler.java, mobile/src/main/java/rs/readahead/washington/mobile/views/activity/CameraActivity.java, mobile/src/main/java/rs/readahead/washington/mobile/views/activity/MainActivity.java, mobile/src/main/java/rs/readahead/washington/mobile/views/activity/MetadataActivity.java, mobile/src/main/java/rs/readahead/washington/mobile/views/adapters/CollectOutboxFormInstanceRecycleViewAdapter.java, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/MicFragment.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/forms/DraftFormsListFragment.java, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/forms/OutboxFormListFragment.java, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/forms/SubmittedFormsListFragment.java, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/uwazi/entry/UwaziEntryFragment.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/uwazi/entry/UwaziFormView.java, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/uwazi/widgets/UwaziLinkWidget.java, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/uwazi/widgets/UwaziQuestionWidget.java, mobile/src/main/java/rs/readahead/washington/mobile/views/interfaces/ISavedFormsInterface.java, mobile/src/main/java/rs/readahead/washington/mobile/views/settings/HideBehindCalculator.kt, mobile/src/main/res/values/strings.xml
T762 - Weird bug on Calculator set up screen - change requested
T768 - Fix audio recording renaming flow
T705 - Check if URL is valid on link property
T554 - Make Tella ask to enable GPS
=> fixes on version code v97

mobile/src/main/java/rs/readahead/washington/mobile/views/activity/MainActivity.java, mobile/src/main/java/rs/readahead/washington/mobile/views/activity/onboarding/OnBoardCalculatorFragment.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/activity/onboarding/OnBoardHideNameLogoFragment.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/settings/CamouflageNameAndLogo.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/settings/HideBehindCalculator.kt, mobile/src/main/res/values/strings.xml, shared-ui/src/main/java/org/hzontal/shared_ui/bottomsheet/BottomSheetUtils.kt
[T764 - Add a bottom sheet warning users that app will close](https://app.asana.com/0/1199579928442791/1202022740542893/f)
=> Add a bottom sheet warning users that app will close

mobile/build.gradle, mobile/src/main/java/rs/readahead/washington/mobile/views/activity/MainActivity.java, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/uwazi/SubmittedPreviewFragment.kt
Fixes:
T676 - Fix Summary UI - changes applied to the submitted entities too
T743 - In an entity, the back button should lead to the Uwazi screen
=> Fixes for v2.0.6

mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/vault/home/HomeVaultFragment.kt, mobile/src/main/res/layout/fragment_general_settings.xml
Pull requests should be opened against the `develop` branch. For more information on contributing to Tella source code, see the [Contributor Guidelines](contributing/contributor_guide.md).
**Description:**
Hide cleaninsight from ui in settings and vault 
https://app.asana.com/0/1199579928442791/1202375630641981/f
**Select the type of change(s) made in this pull request:**
----------------------------------------------------------------------------------------
Fixes #issue-number
*
*
*
=> T836 cleaninsights

mobile/src/main/java/rs/readahead/washington/mobile/views/activity/AudioPlayActivity.java, mobile/src/main/java/rs/readahead/washington/mobile/views/activity/CameraActivity.java, mobile/src/main/java/rs/readahead/washington/mobile/views/activity/CollectFormEntryActivity.java, mobile/src/main/java/rs/readahead/washington/mobile/views/activity/CollectMainActivity.java, mobile/src/main/java/rs/readahead/washington/mobile/views/activity/PhotoViewerActivity.java, mobile/src/main/java/rs/readahead/washington/mobile/views/activity/VideoViewerActivity.java, mobile/src/main/java/rs/readahead/washington/mobile/views/base_ui/BaseActivity.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/MicFragment.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/forms/CollectMainFragment.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/vault/attachements/AttachmentsFragment.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/vault/home/HomeVaultFragment.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/settings/GeneralSettings.kt, shared-ui/src/main/java/org/hzontal/shared_ui/bottomsheet/BottomSheetUtils.kt
Fix tiemout issue when user request permission
=> Fix timeout issue 

mobile/src/main/java/rs/readahead/washington/mobile/util/CamouflageManager.java
T841 - Tella icon visible with calculator camouflage
=> Fix: Hide Tella icon when applying camouflage

mobile/build.gradle, mobile/src/main/java/rs/readahead/washington/mobile/mvp/presenter/CollectCreateFormControllerPresenter.java, mobile/src/main/java/rs/readahead/washington/mobile/views/activity/CollectFormEntryActivity.java, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/forms/SharedFormsViewModel.kt, mobile/src/main/res/layout/blank_collect_form_row.xml, shared-ui/src/main/res/layout/standar_sheet_layout.xml
Increase padding on standard sheet layout,
Decrease size of star - fvorites odk forms,
Revert Javarosa,
fix onPause FormEntryActivity
=> Final fixes for version code 125

mobile/src/main/java/rs/readahead/washington/mobile/views/activity/AudioPlayActivity.java, mobile/src/main/java/rs/readahead/washington/mobile/views/activity/PhotoViewerActivity.java, mobile/src/main/java/rs/readahead/washington/mobile/views/activity/VideoViewerActivity.java, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/vault/attachements/AttachmentsFragment.kt
T834 - Change order of dialogs on exporting files with or without metadata
=> Change order of dialogs on exporting files with or without metadata

mobile/build.gradle, mobile/src/main/java/rs/readahead/washington/mobile/data/database/DataSource.java, mobile/src/main/java/rs/readahead/washington/mobile/data/sharedpref/Preferences.java, mobile/src/main/java/rs/readahead/washington/mobile/data/sharedpref/SharedPrefs.java, mobile/src/main/java/rs/readahead/washington/mobile/mvp/presenter/CollectCreateFormControllerPresenter.java, mobile/src/main/java/rs/readahead/washington/mobile/util/TellaUpgrader.java, mobile/src/main/java/rs/readahead/washington/mobile/views/activity/MainActivity.java, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/forms/BlankFormsListFragment.java, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/forms/SharedFormsViewModel.kt, mobile/src/main/res/values/config.xml, mobile/src/main/res/values/strings.xml, shared-ui/src/main/java/org/hzontal/shared_ui/bottomsheet/BottomSheetUtils.kt
- Update javarosa lib
- Flush all forms in the app
- Fixed link to the privacy policy page
=> Javarosa upgrade

shared-ui/src/main/java/org/hzontal/shared_ui/bottomsheet/CustomBottomSheetFragment.kt, shared-ui/src/main/res/values/styles.xml
Fix focus bottomsheet EditText
=> EditText Focus fix

mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/vault/attachements/AttachmentsFragment.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/vault/attachements/AttachmentsPresenter.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/vault/attachements/IAttachmentsPresenter.kt, mobile/src/main/res/layout/fragment_vault_attachments.xml, mobile/src/main/res/values/strings.xml, mobile/src/main/res/values/vault_strings.xml
add a snackBar when file is moved
=> add a snackBar when file is moved 

mobile/src/main/java/rs/readahead/washington/mobile/media/MediaFileHandler.java, mobile/src/main/java/rs/readahead/washington/mobile/mvp/presenter/GalleryPresenter.java, mobile/src/main/java/rs/readahead/washington/mobile/mvp/presenter/MediaImportPresenter.java, mobile/src/main/java/rs/readahead/washington/mobile/mvp/presenter/QuestionAttachmentPresenter.java, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/vault/attachements/AttachmentsFragment.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/vault/attachements/AttachmentsPresenter.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/vault/attachements/IAttachmentsPresenter.kt, mobile/src/main/res/values-ar/strings.xml, mobile/src/main/res/values-es/strings.xml, mobile/src/main/res/values-fr/strings.xml, mobile/src/main/res/values-kac/strings.xml, mobile/src/main/res/values-my-rMM/strings.xml, mobile/src/main/res/values/strings.xml, mobile/src/main/res/values/styles.xml, shared-ui/src/main/java/org/hzontal/shared_ui/bottomsheet/BottomSheetUtils.kt, shared-ui/src/main/java/org/hzontal/shared_ui/extensions/ProgressExtensions.kt, shared-ui/src/main/res/layout/layout_progess_sheet.xml, shared-ui/src/main/res/layout/standar_sheet_layout.xml, shared-ui/src/main/res/values/dimens.xml, shared-ui/src/main/res/values/styles.xml
adding import files bottom sheet progress
=> adding import files bottom sheet progress

mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/vault/attachements/AttachmentsPresenter.kt, shared-ui/src/main/java/org/hzontal/shared_ui/bottomsheet/BottomSheetUtils.kt
add closing automatically when the import is complete.
=> add closing automatically when the import is complete in the bottom sheet

mobile/src/main/java/rs/readahead/washington/mobile/views/activity/MetadataActivity.java
If the airplane mode and varification mode is on, open location setting if needed.
=> Location Setting in the airplane mode

build.gradle, mobile/build.gradle, mobile/src/main/java/rs/readahead/washington/mobile/data/database/DataSource.java, mobile/src/main/java/rs/readahead/washington/mobile/domain/entity/EntityStatus.kt, mobile/src/main/java/rs/readahead/washington/mobile/mvp/presenter/CollectCreateFormControllerPresenter.java, mobile/src/main/java/rs/readahead/washington/mobile/mvp/presenter/TellaFileUploadSchedulePresenter.java, mobile/src/main/java/rs/readahead/washington/mobile/util/Extensions.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/activity/SplashActivity.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/activity/onboarding/OnBoardingActivity.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/base_ui/BaseActivity.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/dialog/reports/step3/LoginReportsFragment.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/MicFragment.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/forms/CollectMainFragment.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/forms/SharedFormsViewModel.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/reports/ReportsViewModel.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/reports/entry/ReportsEntryFragment.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/reports/send/ReportsSendFragment.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/uwazi/OutboxUwaziFragment.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/uwazi/SubmittedUwaziFragment.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/uwazi/UwaziFragment.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/uwazi/widgets/ReportsFormEndView.java, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/vault/adapters/VaultAdapter.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/vault/attachements/AttachmentsPresenter.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/vault/home/HomeVaultFragment.kt, mobile/src/main/res/layout/fragment_collect_main.xml, mobile/src/main/res/layout/fragment_reports.xml, mobile/src/main/res/layout/fragment_uwazi.xml
T-And-1100 - Once Uwazi reports go the the outbox they are stuck there
T-And-1098 - Cannot connect to Tella Web server on version 147
T-And-1082 - Push new translations from Lolakalize
T-And-1093 - Review Uwazi submission implementation
T-And-1056 - Clicking a report on the outbox tab should go to the details/pause state (it should not submit it)
T-And-1096 - Missing or duplicated elements on the homescreen (caché problem??) 
T-And-1108 - Refresh problem on server connections
T-And-1064 - Remove the Verification iforrmation setting and the background submission on the Server setting screen
T-And-1102 - The server connected screen should be shown after login into Tella Web project
=> Fix  Asana  bugs

mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/forms/BlankFormsListFragment.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/reports/ReportsViewModel.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/reports/entry/ReportsEntryFragment.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/reports/send/ReportsSendFragment.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/uwazi/entry/UwaziEntryFragment.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/uwazi/send/UwaziSendFragment.kt, mobile/src/main/res/layout/fragment_send_report.xml
Fix :
T-And-1119 - Start submitting a report when I press submit
T-And-1126 - Tapping resume moves the report to outbox
=> Release bug fixes

mobile/src/main/java/rs/readahead/washington/mobile/data/sharedpref/Preferences.java, mobile/src/main/java/rs/readahead/washington/mobile/data/sharedpref/SharedPrefs.java, mobile/src/main/java/rs/readahead/washington/mobile/media/MediaFileHandler.java, mobile/src/main/java/rs/readahead/washington/mobile/views/settings/SecuritySettings.kt, mobile/src/main/res/layout-hdpi/fragment_security_settings.xml, mobile/src/main/res/layout/fragment_security_settings.xml, mobile/src/main/res/values-ar/strings.xml, mobile/src/main/res/values-be/strings.xml, mobile/src/main/res/values/strings.xml
T-And-1167 - Implement EXIF deletion when importing files
=> EXIF deletion when importing files

mobile/src/main/AndroidManifest.xml, mobile/src/main/java/rs/readahead/washington/mobile/MyApplication.java, mobile/src/main/java/rs/readahead/washington/mobile/media/MediaFileHandler.java, mobile/src/main/java/rs/readahead/washington/mobile/views/activity/camera/CameraActivity.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/activity/viewer/PhotoViewerActivity.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/dialog/reports/edit/EditTellaServerFragment.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/forms/BlankFormsListFragment.kt, tella-locking-ui/src/main/java/com/hzontal/tella_locking_ui/ui/DeviceCredentialsUnlockActivity.java, tella-locking-ui/src/main/java/com/hzontal/tella_locking_ui/ui/password/PasswordUnlockActivity.kt, tella-locking-ui/src/main/java/com/hzontal/tella_locking_ui/ui/pin/PinUnlockActivity.kt, tella-locking-ui/src/main/java/com/hzontal/tella_locking_ui/ui/pin/calculator/Evaluator.java
- Fix calculation of %
- Fix showing metadata menu item in PhotoViewerActivity
=> Fixes for 2.4 159

mobile/src/main/java/rs/readahead/washington/mobile/views/activity/onboarding/OnBoardingActivity.kt, tella-locking-ui/src/main/res/layout/activity_pin.xml
Fix the Onboarding flow to connect to an ODK server
=> T-And-875 - Fix the Onboarding flow to connect to an ODK server

mobile/src/main/java/rs/readahead/washington/mobile/bus/event/EditMediaSavedEvent.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/reports/ReportsViewModel.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/vault/attachements/AttachmentsFragment.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/vault/edit/VaultEditFragment.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/vault/home/HomeVaultFragment.kt, mobile/src/main/res/layout/fragment_vault_edit.xml, mobile/src/main/res/values/strings.xml, shared-ui/src/main/res/layout/vault_actions_sheet_layout.xml, tella-locking-ui/src/main/java/com/hzontal/tella_locking_ui/ui/pin/calculator/Evaluator.java
T-And-1216 -fix,
T-And-1300 - Put the "image > more" Actions elements in the correct order,
T-And-1301 - Missing whole EXIT EDITOR Flow
=> Fixes on v161

mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/vault/attachements/AttachmentsFragment.kt, shared-ui/src/main/java/org/hzontal/shared_ui/bottomsheet/VaultSheetUtils.kt
T-And-1305 - Hide Edit button from the menu for all file types that are not Images
=>  Hide Edit button from the menu for all non image file types

mobile/src/main/java/rs/readahead/washington/mobile/media/MediaFileHandler.java, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/vault/attachements/AttachmentsFragment.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/settings/SecuritySettings.kt, mobile/src/main/res/layout-hdpi/fragment_security_settings.xml, mobile/src/main/res/layout/fragment_security_settings.xml
-T-And-1318 - Deleting a folder doesn't delete the files inside (they still appear on Images folder).
T-And-1317 - Restrict import to a single file
=> Bug fixes Release 2.4.0

mobile/src/main/java/rs/readahead/washington/mobile/views/settings/GeneralSettings.kt
All checkboxes are turn on after going outside of the language selector
=> Fix T-And-1324 - Bug on checkboxes

mobile/src/main/java/rs/readahead/washington/mobile/views/dialog/reports/step1/EnterUploadServerFragment.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/dialog/reports/step3/LoginReportsFragment.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/dialog/uwazi/step1/EnterServerFragment.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/dialog/uwazi/step3/LoginFragment.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/dialog/uwazi/step4/TwoFactorAuthenticationFragment.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/feedback/SendFeedbackFragment.kt, shared-ui/src/main/java/org/hzontal/shared_ui/bottomsheet/CustomBottomSheetFragment.kt, shared-ui/src/main/java/org/hzontal/shared_ui/bottomsheet/KeyboardUtil.java, shared-ui/src/main/java/org/hzontal/shared_ui/utils/DialogUtils.kt, shared-ui/src/main/res/layout/blue_sheet_rename.xml
T-And-1309 - Display issues for bottom sheet too name/rename file or folder
=> Fix T-And-1309

mobile/src/main/java/rs/readahead/washington/mobile/views/activity/viewer/VideoViewerActivity.kt, mobile/src/main/res/layout/activity_video_viewer.xml
T-And-1337 - Missing loader wheel on video player
Replace deprecated SimpleExoPlayer
Fix toolbar
=> Fix video player

shared-ui/src/main/java/org/hzontal/shared_ui/bottomsheet/CustomBottomSheetFragment.kt
Fix T808 - Back arrow w should close bottom sheets
=> T808 - Back arrow w should close bottom sheets

mobile/src/main/java/rs/readahead/washington/mobile/data/reports/repository/ReportsRepositoryImp.kt, mobile/src/main/java/rs/readahead/washington/mobile/domain/repository/reports/ReportsRepository.kt, mobile/src/main/java/rs/readahead/washington/mobile/mvp/presenter/AudioCapturePresenter.java, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/reports/ReportsViewModel.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/reports/send/ReportsSendFragment.kt, mobile/src/main/res/layout/fragment_send_report.xml
Fix problems loading report from outbox if there is no internet connection
=> T-And-1335 - Problems loading report from outbox

mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/uwazi/entry/UwaziParser.kt
fix T-And-1519 - Unexpected error when submitting an entity to uwazi related to multi select
=> fix uwazi multiselect problem

build.gradle, mobile/build.gradle, mobile/src/main/java/rs/readahead/washington/mobile/views/dialog/TellaUploadServerDialogFragment.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/dialog/UwaziServerDialogFragment.kt, mobile/src/main/res/values/divviup.xml
Fix problem related to build the project on the master branch.
=> Make Master buildabe

mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/vault/attachements/AttachmentsFragment.kt, mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/vault/attachements/AttachmentsViewModel.kt, mobile/src/main/res/values/strings.xml, shared-ui/src/main/java/org/hzontal/shared_ui/bottomsheet/VaultSheetUtils.kt
T-And-1566 - Bug when rename image with the same name from folder images
=> Fix T-And-1566

mobile/build.gradle, mobile/src/main/res/values-ldrtl/consts.xml, mobile/src/main/res/values/config.xml
=> Release 2.14.0 "196"

mobile/src/main/java/org/horizontal/tella/mobile/data/database/DataSource.java, mobile/src/main/java/org/horizontal/tella/mobile/data/database/DropBoxDataSource.java, mobile/src/main/java/org/horizontal/tella/mobile/data/database/GoogleDriveDataSource.java, mobile/src/main/java/org/horizontal/tella/mobile/data/database/HorizontalSQLiteOpenHelper.java, mobile/src/main/java/org/horizontal/tella/mobile/data/database/NextCloudDataSource.java, mobile/src/main/java/org/horizontal/tella/mobile/data/database/ResourceDataSource.java, mobile/src/main/java/org/horizontal/tella/mobile/data/database/UwaziDataSource.java, mobile/src/main/java/org/horizontal/tella/mobile/util/CamouflageManager.java, mobile/src/main/java/org/horizontal/tella/mobile/util/ThemeStyleManager.kt, tella-locking-ui/src/main/java/com/hzontal/tella_locking_ui/Constants.kt
rename classes and fix alias naming
=> rename classes and fix alias naming 

mobile/src/main/java/org/horizontal/tella/mobile/views/activity/CollectFormEntryActivity.kt, mobile/src/main/java/org/horizontal/tella/mobile/views/fragment/uwazi/entry/UwaziEntryFragment.kt
=> fix gps bugs 

mobile/build.gradle
=> upgrade version code

mobile/src/main/java/org/horizontal/tella/mobile/data/repository/UwaziRepository.kt, mobile/src/main/java/org/horizontal/tella/mobile/data/rest/IUwaziApi.kt, mobile/src/main/java/org/horizontal/tella/mobile/domain/repository/uwazi/IUwaziUserRepository.kt, mobile/src/main/java/org/horizontal/tella/mobile/views/fragment/uwazi/entry/SharedUwaziSubmissionViewModel.kt, mobile/src/main/res/layout/activity_camera.xml, mobile/src/main/res/values-ar/strings.xml, mobile/src/main/res/values-bn/strings.xml, mobile/src/main/res/values-es-rCU/strings.xml, mobile/src/main/res/values-es/strings.xml, mobile/src/main/res/values-fa-rIR/strings.xml, mobile/src/main/res/values-fr/strings.xml, mobile/src/main/res/values-kac/strings.xml, mobile/src/main/res/values-my/strings.xml, mobile/src/main/res/values-pt/strings.xml, mobile/src/main/res/values-ru/strings.xml, mobile/src/main/res/values-sn-rZW/strings.xml, mobile/src/main/res/values-tr/strings.xml, mobile/src/main/res/values-vi/strings.xml, mobile/src/main/res/values/strings.xml
handling submission  issue on uwazi
=> fix T-And-1701 - Uwazi integration not working - not usable (submission  issue)
